#Initalize the WILDlings cards
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Silence The Wall")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Rattleshirt's Raiders")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Preemptive Raid")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Skinchanger Scout")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "The Horde Descends")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Crow Killers")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Mammoth Riders")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "A King Beyond The Wall")
Card.create(:deck_type_id => DeckType::WILDLINGS, :name => "Massing On The Milkwater")